---
name: New Action request
description: Suggest an idea for a new app or action
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: New Action request
      description: A clear and concise description of what the problem is and what the new action would accomplish. Please describe.
      placeholder: |
        Ex. It would be great to have an action that would ...
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Checklist
      description: Items that need to be completed along with the creation of the new App or Action (to be filled out later when the action is being developed)
      options:
        - label: Evaluate existing solutions before developing (search github.com/marketplace)
          required: false
        - label: Update [GitHub Actions section of README](https://github.com/github/github-ospo?tab=readme-ov-file#tools-created-by-github-ospo) linking to the new App or Action
          required: false
        - label: Write a blog post on [GitHub Blog](https://github.blog/) about the new App or Action
          required: false
        - label: Add App or Action to [todogroup/awesome-ospo](https://github.com/todogroup/awesome-ospo) via pull request
          required: false
