name: Monthly contributor reports
on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 1 * *"

permissions:
  discussions: write

jobs:
  contributor_report:
    name: contributor reports
    runs-on: ubuntu-latest

    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          # Calculate the first day of the previous month
          start_date=$(date -d "last month" +%Y-%m-01)

          # Calculate the last day of the previous month
          end_date=$(date -d "$start_date +1 month -1 day" +%Y-%m-%d)

          #Set an environment variable with the date range
          echo "START_DATE=$start_date" >> "$GITHUB_ENV"
          echo "END_DATE=$end_date" >> "$GITHUB_ENV"

      - name: Run contributor action
        uses: github/contributors@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          START_DATE: ${{ env.START_DATE }}
          END_DATE: ${{ env.END_DATE }}
          REPOSITORY: "github/go-spdx,github-community-projects/internal-contribution-forks,github/stale-repos,github/evergreen,github/issue-metrics,github/github-ospo,github/contributors,github/automatic-contrib-prs,github/cleanowners"
          SPONSOR_INFO: "true"
          LINK_TO_PROFILE: "true"

      - name: Create GitHub Discussion
        uses: abirismyname/create-discussion@v2.1.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Thank you Contributors!"
          body-filepath: ./contributors.md
          repository-id: "R_kgDOJDwwMQ"
          category-id: "DIC_kwDOJDwwMc4CUmf8"
